tokenizer:
  id: 'togepi-bbpe-uncased'
  args:
    name: 'togepi-bbpe-uncased'
    num_merges: 50000
    min_frequency: 2
    special_toks:
      'pad': '<|pad|>'
      'unk': '<|unk|>'
      'eos': '<|endoftext|>'
    lowercase: True
    punct_behavior: 'contiguous'
    padding_side: 'right'
    truncation_side: 'right'
